name: Working Dirs and Shells
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working Directory & List Files
            run: |
             pwd
             ls -a
             